"""
UiPath AI Export - Prompts

Prompt templates paired with the purposes defined in ai_export.py (PURPOSES dict -
purpose keys must match).

Project-scope purposes: "debug" (despite the key name, this is now an *architecture*
review - see ARCHITECTURE_DEBUG_PROMPT_TASK below for why), "business_doc".
File-scope purposes: "file_summary", "file_debug" - two separate prompts (replacing
the old single "file_deep_dive") so a reader who just wants to understand the file
isn't handed the same prompt as someone hunting a specific bug in it. ai_export.py's
PURPOSES dict (and whatever builds AI_FILE_EXPORTS) needs a matching entry for each
of these four keys.

Each prompt is built from two parts, concatenated by build_prompt():
1. SCHEMA_EXPLAINER - a single shared explanation of the JSON shape ai_export.py
   produces. Written once here rather than per-purpose, since the shape itself
   doesn't change between purposes (only which tags/fields survive the trim) - a
   duplicated explanation per prompt would just be more tokens saying the same thing.
   This is itself part of the token-saving strategy discussed earlier: an AI that's
   told up front what `decl_id`-less refs, `key_arguments` vs `assignments`, and
   branch `steps` mean doesn't have to spend its own reasoning inferring the schema
   from examples.
2. A purpose-specific task instruction - what to actually do with the data once the
   AI understands the shape.

The final text sent to an AI chat is: PROMPT + the ai_export.py output, concatenated
by the UI layer (the "Copy" button in the project_map.html modal) - this module only
builds the instructional prefix, not the combined payload. Keeping that concatenation
in the UI layer (rather than doing it here) means the same prompt text can be shown
to the user for review before copying, separately from the data block.
"""

SCHEMA_EXPLAINER = """\
You will receive a structured export of a UiPath RPA project, generated by a custom \
scanner tool (not raw XAML). Here is how to read it:

- The export is organized per workflow file (one JSON block per .xaml file), each \
under a "### <relative_path>" heading.
- "arguments": the file's public parameters (name, direction In/Out/In-Out, type) - \
this is the file's "signature", what it expects to receive and return.
- "variables": internal variables declared in the file, with their name, type, and \
the container (scope) they're declared in.
- "invokes": other workflow files this file calls (InvokeWorkflowFile), including \
"argument_bindings" - which expression is passed to which argument of the called \
file. This is the actual cross-file data flow, not just a call graph.
- "invoked_by": which other files call this one (the reverse of "invokes").
- "activity_flow": the ordered tree of activities in the file, structured as it \
actually appears (not flattened). Two node shapes appear in this tree:
  - {"type": "activity", "tag": <UiPath activity type>, "name": <display name>, ...}: \
a single step. May include "assignments" (To/Value pairs, for Assign activities), \
"key_arguments" or "arguments" (the activity's most relevant parameter values), an \
"annotation" (a developer-written comment on that specific activity - treat these as \
high-trust hints about intent), and "children" (nested activities, e.g. inside a \
Sequence).
  - {"type": "branch", "kind": "if"/"switch"/"trycatch", "condition": ..., \
"branches": [{"label": ..., "condition": ..., "steps": [...]}]}: a control-flow \
split. Each branch's "label" tells you which path it is (e.g. "Then", "Else If", \
"Case X", "Try", "Catch (SomeException)", "Finally"), and "steps" is that branch's \
own activity list, in the same two-shape format.
- Expression text (e.g. inside "value", "condition", "assignments") is UiPath's \
VB-style expression syntax (e.g. "[myVariable]", "myVar.ToString()") - read it as \
code, not as literal display text.
"""


# Appended only to the single-file export prompt (see FILE_DEEP_DIVE_PROMPT_TASK
# below), since it explains a section (Neighboring files) that only ever appears in
# a single-file export - the whole-project export has no need for it, as every
# file's own full section is already present elsewhere in that same export.
FILE_SCHEMA_ADDENDUM = """\
You are receiving a **single workflow file** from a larger UiPath project, not the \
whole project - do not assume you are seeing every file. After the file's own \
"### <relative_path>" section, a "## Neighboring files (signatures only, not full \
flow)" section lists the files it calls and the files that call it, each shown only \
as "<path>: <arguments>" (its public In/Out contract) - not that neighbor's internal \
logic. Use these to understand what data crosses each call boundary, but do not \
speculate about a neighbor's internal implementation beyond what its signature tells \
you.
"""


ARCHITECTURE_DEBUG_PROMPT_TASK = """\
Your task: review this UiPath project as a senior RPA architect auditing its \
*structure* - not a line-by-line bug hunt inside individual files, and not a \
functional summary. Judge whether the project is put together well.

If an "## Additional context" section appears below (before the project's export \
data), the user has flagged a specific area of concern or suspicion - e.g. a \
particular file, folder, or process they suspect is fragile or badly structured. \
Treat it as a lead to prioritize, but still review the whole project as described \
below rather than looking only at what was mentioned - a suspicion about one area \
doesn't mean other areas are exempt. If no such section is present, review the \
project with no particular starting point.

Concretely, look for:
- Control-flow shape: files that mix orchestration and detailed implementation \
instead of delegating cleanly, overly deep nesting of branches, or a "god file" that \
does too much and should be split into smaller invoked workflows.
- Dependency structure: the invokes/invoked_by graph across files - circular or \
redundant invocation chains, a low-level file invoked from many unrelated places \
(signals it should be a shared library step, or that responsibilities aren't well \
separated), or a dynamic (non-literal) InvokeWorkflowFile path that breaks static \
traceability of the graph.
- Contract consistency across boundaries: argument direction (In/Out/In-Out) that \
doesn't match how the callee actually uses it based on argument_bindings, or \
inconsistent naming/typing for what is conceptually the same piece of data as it \
crosses multiple file boundaries.
- Error-handling as a project-wide pattern: is exception handling applied \
consistently across files that do similar risky work (UI automation, file/Excel/API \
calls), or does it exist in some files and not others with no apparent reason - \
inconsistency here is itself an architectural finding, distinct from a single \
missing TryCatch in one file.
- Retry/logging as a project-wide pattern: same idea - is there a consistent \
strategy for retrying transient failures and logging for diagnosability, or is it \
ad hoc per file.

For each finding, cite the specific files (and, where relevant, activities) \
involved, explain concretely why it's an architectural weakness rather than a local \
one, and suggest how you'd restructure it. Prioritize findings by how much they'd \
affect the project's maintainability or reliability at scale, not by how many you \
can list. This is not the place to flag a single isolated bug inside one file's \
internal logic - if you find one, mention it only if it's evidence of the broader \
pattern.

Only report a finding you can point to concretely in the data above - do not \
manufacture a weak or speculative one just to have something to say. If the \
project's structure is genuinely sound (clean delegation between files, consistent \
error-handling/retry/logging patterns, no problematic dependency shapes), say that \
plainly and name what's done well, rather than inventing an architectural weakness \
that isn't actually there. "No significant architectural issues found" is a valid \
and useful conclusion when it's true.
"""


BUSINESS_DOC_PROMPT_TASK = """\
Your task: write a functional/business specification document explaining what this \
UiPath project does, for a reader who is NOT a developer (e.g. a business \
stakeholder, process owner, or new team member who needs to understand the process \
without reading code).

If an "## Additional context" section appears below (before the project's export \
data), the user has told you what to focus on or who the document is for - e.g. a \
specific process area to expand on, or a particular audience (finance, compliance, \
a new hire). Follow that emphasis, but still produce a complete document using the \
structure below rather than dropping sections it doesn't mention. If no such \
section is present, write for the general non-developer reader described above.

Throughout the entire document, translate every technical identifier into plain \
language - never write a raw argument name, variable name, activity tag, file path, \
or expression exactly as it appears in the export. Describe what it represents \
instead (e.g. "the case reference it receives," not the argument name itself; "the \
configured file-share path," not the literal config key). This applies to every \
section below, not just the ones about process steps - a parameter list or a \
config summary is exactly where identifiers tend to leak in verbatim, so translate \
them there as deliberately as anywhere else.

Structure the document as:
1. **Process overview** - one paragraph: what business process does this automation \
perform, start to end, in plain language.
2. **Trigger & inputs** - what starts this process and what information it needs, \
described in plain business terms (e.g. "the case reference to process" or "the \
customer's account number") rather than by the entry-point file's literal argument \
names.
3. **Main process steps** - walk through the actual business logic in order (what \
decisions are made and why, referencing branch conditions in plain language, not as \
code expressions), organized by the workflow file structure. Skip low-level \
technical steps (e.g. individual UI clicks/keystrokes) unless they are the actual \
point of a step - describe what is accomplished, not how each activity is \
configured.
4. **Key decision points** - call out each meaningful branch (If/Switch) in the \
process and explain, in business terms, what determines which path is taken.
5. **Dependencies & configuration** - if project metadata or config values are \
included, summarize in plain terms what external systems, files, or settings this \
process depends on - describe what each one is for, not its raw key or path.

Use developer-written annotations wherever present as your primary source of intent - \
they represent what the developer explicitly wanted future readers to know. Do not \
speculate about business rules not evidenced in the data; if a step's business \
purpose isn't clear from names/annotations, say so rather than inventing a rationale.
"""


FILE_SUMMARY_PROMPT_TASK = """\
Your task: explain this ONE workflow file for two different readers in two clearly \
separated parts - a business reader first, a technical reader second. This is the \
single-file counterpart to a project-wide spec document, but grounded in this \
file's actual conditions, arguments, and variables for the technical part, while \
staying fully readable to someone who has never seen the underlying code for the \
business part.

If an "## Additional context" section appears below (before the file's export \
data), the user has told you what to focus on within this file, or who the \
explanation is for - e.g. a specific branch or invoked neighbor to go deeper on, or \
a particular reader (someone new to the naming conventions, a tester rather than a \
developer). Follow that emphasis, but still give both parts below rather than \
dropping one. If no such section is present, explain the file for the general \
readers described below.

Structure the explanation as two clearly labeled parts:

1. **What this file does (business language)** - one or two short paragraphs \
describing the business action this file performs and its place in the larger \
process, written the way you'd explain it to a process owner who has never opened \
the workflow and never will. Describe what it needs as input and what it hands off \
to the next step in plain terms (e.g. "a reference to the case being processed"), \
what the file actually accomplishes end to end, and - using the "Neighboring files" \
section - what happens just before and after it in the process, without speculating \
about a neighbor's internal logic beyond what its signature tells you. This part \
must not contain a single argument name, variable name, activity tag, file path, or \
expression as written in the export (e.g. write "the file path it receives," never \
the literal argument identifier). If a decision point matters at this level, \
describe what it means for the process (e.g. "if more than one matching document \
is found, it's treated differently than a single match") without naming the \
underlying variable or condition - that belongs in part 2.

2. **How the logic flows (technical detail)** - here, be fully concrete: walk \
through the activity_flow in order, citing the file's actual argument names, \
variable names, and activity tags as they appear in the export, and state each \
meaningful branch condition both as its literal expression and a one-line plain \
gloss of what it checks. Trace what each invoked neighbor is given and what it \
hands back, and what ultimately determines the file's Out arguments (or, if it has \
none, what marks the file as having completed successfully). Skip individual UI \
automation steps that don't affect data or control flow (e.g. a click that's pure \
navigation with no bearing on what happens next); keep any step - UI-driven or not \
- that a developer would need in order to reproduce or modify the logic.

Use developer-written annotations wherever present as your primary source of intent \
in both parts. Do not speculate about intent that isn't evidenced by \
names/annotations/conditions - if something isn't clear from the data, say so \
rather than inventing a rationale.
"""


FILE_DEBUG_PROMPT_TASK = """\
Your task: act as a developer investigating a specific problem in this ONE workflow \
file - a targeted diagnosis, not a general code review and not a project-wide check.

If a "## Reported issue" section appears below (before the file's export data), it \
describes the symptom the user is actually seeing. Treat it as the primary lead: \
trace the specific arguments, variables, and activities that could plausibly produce \
that symptom, and identify the most likely root cause(s) - cite the exact activity, \
argument, or variable responsible, and explain the mechanism (why the flow produces \
that symptom), not just where it might be. If nothing in the data actually explains \
the reported symptom, say so directly rather than inventing a plausible-sounding but \
unsupported cause - note what you checked and ruled out, and what additional \
information (e.g. runtime logs, the actual input values used) would be needed to go \
further.

If no "## Reported issue" section is present, perform a general debugging pass over \
this file instead, looking for the kinds of concrete defects that actually break a \
single file at runtime:
- Argument direction mismatches: an argument declared In but whose value the flow \
treats as something it should be writing back, an Out argument that is never \
assigned on some execution path (e.g. inside only one branch of an If, or not in a \
Catch), or an In/Out argument that's read before it's ever been given a value on \
some path.
- Variables read before being assigned on some path, assigned in one branch but \
relied upon after a branch that doesn't set it, or shadowing/reuse that could carry \
a stale value across an unrelated part of the flow.
- Unsafe assumptions in expressions: collection/array access without a bounds or \
null check, division that could hit zero, string operations on a value that might be \
empty or Nothing.
- Exception handling gaps around this file's own risky activities (UI automation, \
file/Excel/API calls), or a Catch broad enough to be swallowing the actual error \
instead of surfacing it.
- A dynamic (non-literal) InvokeWorkflowFile path or argument binding whose actual \
target/value can't be confirmed from this data alone - flag it as unverifiable \
rather than guessing what it resolves to.

If you don't find any real instance of the issues above, say so plainly rather than \
manufacturing a marginal or speculative one just to produce output - a file with no \
notable defects is a valid and useful finding, not an incomplete answer.

Either way, cite the specific activity (by name/tag), argument, or variable involved \
in each point you raise, and state your confidence - some causes will be certain \
from the data shown, others only plausible candidates worth checking.
"""


PROMPTS: dict[str, str] = {
    "debug": SCHEMA_EXPLAINER + "\n" + ARCHITECTURE_DEBUG_PROMPT_TASK,
    "business_doc": SCHEMA_EXPLAINER + "\n" + BUSINESS_DOC_PROMPT_TASK,
    "file_summary": SCHEMA_EXPLAINER + "\n" + FILE_SCHEMA_ADDENDUM + "\n" + FILE_SUMMARY_PROMPT_TASK,
    "file_debug": SCHEMA_EXPLAINER + "\n" + FILE_SCHEMA_ADDENDUM + "\n" + FILE_DEBUG_PROMPT_TASK,
}


def build_prompt(purpose_key: str) -> str:
    """
    Returns the instructional prefix for the given purpose. Raises KeyError on an
    unregistered purpose key, same contract as ai_export.build_ai_export - a caller
    passing an unknown key is a wiring bug (the UI is expected to only offer keys
    that exist in both PROMPTS here and PURPOSES in ai_export.py), not user input to
    validate defensively.
    """
    return PROMPTS[purpose_key]


def build_full_payload(purpose_key: str, export_text: str, user_notes: str = "") -> str:
    """
    Convenience combiner: prompt + a blank line + the ai_export.py output, ready to
    paste as-is into an AI chat. The UI layer is free to do this concatenation itself
    instead (e.g. to show the prompt and data as separate preview panes before
    copying) - this exists for the common single-string case (e.g. a CLI test run).

    user_notes is optional free text from the user, inserted as a marker section
    right before the export data - every purpose explains in its own task
    instruction how it's used, and all of them fall back to their default behavior
    when it's left blank. The marker's header depends on what the note actually
    represents for that purpose: "file_debug" frames it as a reported symptom to
    diagnose ("## Reported issue"); the other three ("debug", "business_doc",
    "file_summary") frame it as context or a focus/audience to prioritize, since
    none of them are diagnosing a single bug ("## Additional context").
    """
    if not user_notes.strip():
        return f"{build_prompt(purpose_key)}\n\n---\n\n{export_text}"
    header = "## Reported issue" if purpose_key == "file_debug" else "## Additional context"
    return f"{build_prompt(purpose_key)}\n\n{header}\n{user_notes.strip()}\n\n---\n\n{export_text}"


if __name__ == "__main__":
    import sys

    key = sys.argv[1] if len(sys.argv) > 1 else "debug"
    print(build_prompt(key))